name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

  build:
    name: Build & Publish Release
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Install Linux Build Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfuse2
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build frontend
        run: pnpm run frontend:build

      - name: Build and Publish Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            pnpm run build:linux
          elif [ "$RUNNER_OS" == "Windows" ]; then
            pnpm run build:win
          elif [ "$RUNNER_OS" == "macOS" ]; then
            pnpm run build:mac
          fi
        shell: bash
